 const actionsTypes = {
  EDIT_BOT_ELEMENT: 'EDIT_BOT_ELEMENT',
  SAVE_BOT_ELEMENTS_REQUEST: 'SAVE_BOT_ELEMENTS_REQUEST',
  SAVE_BOT_ELEMENTS: 'SAVE_BOT_ELEMENTS',
  SAVE_BOT_ELEMENTS_ERROR: 'SAVE_BOT_ELEMENTS_ERROR',
  UPDATE_BOT_DATA: 'UPDATE_BOT_DATA'
}

module.exports = actionsTypes;