export const actionTypes = {
  GET_BOT_LIST_REQUEST: 'GET_BOT_LIST_REQUEST',
  GET_BOT_LIST_SUCCESS: 'GET_BOT_LIST_SUCCESS',
  GET_BOT_LIST_ERROR: 'GET_BOT_LIST_ERROR',
  GET_BOT_LIST_UPDATE: 'GET_BOT_LIST_UPDATE'
}

export default actionTypes;